sudo: true
dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

env:
  #- secure: "0BiU3csFt1eKre754LtUdM4NmN2nqYc34F/a7XGzFXzP3sn8USfhq4elnOQDtSlDcfGFKEBrls06I2ytK88W41GBYNqZQITBIukOHS5cRbWFM2xeEMbgRDv+L1ynQWSqAAYR+76NxSxU2h4dLz7YN95WQev2aH396QCWXf/e0X4M0gjsdBUT6ZtsVYfI7h1FERY92Dkf9ShGkhplZeCkiHvBU2VQwO2E5pKlNp/SJp28ERXcgIGEI880/tAGoDqxAuco+ZIiqsq9Zni7r/ucBVoDRr2O6vF5hklhIfHl+/wIbY5Y8hgZB9nziyqJ4Vi27G8KnZufCCRvMY39KP9X6wmX5TjeFqRDhmWDFd1RWJ22ichr0Jx0zOGHwY5wrH/6OC48ukqH002u7QvzzGoMIPREw8W+5CjF8qTUbiybI73ie9ZIWaseGBeA+c0x6JNuoP89d2QOM818yT2I/hsFRhs4V/tkQfd3uROCxpsv+VOehF6zyXcVLyf2HvNZBQbrrR0qpm0hNnn3ApWSFntKStUZceZmiPjhKABgVpOfkZd/2u7WMbR7vfm2G2/bH/uJeMvbVMqMVrulA7hAMgLlmbi0S8F2j68j+NQjDH0EjOI/xp+1f0stz2fU5ewxIgs8S/V+Ue9EYrSPrMS21e16toBzyYCLoVk85/FUrxJcxrw="
  - secure: "FgMMBxJS43S88ab4uspgssy2Oz7LOlkGPLmVrPYWlOKHn/7Eb4fKYKO1uiTGASuaelHZfXa0dGG1wetMsw3UtUB4I1JB1QkSK+uzD0KiGktNOO+cjFElZpFV/cUnDggWuIeVyA4OXDV0qoFDoqSETTKHM9t+vGDKGQ4edIITz1ra+UKkr7EV12F7vhvkd17hNN7iRVv1uhTc4nxN0z/3zQPuKJJmi4NSkmhFsUyioIyOT4hnjXOyUn+4lku2CeGG6kXfzutQNd6vXzFym/A7IC9mwX2ibHYsIDR5coruHk+7aXpVLnsJ3sGCp18GRwcagldDG/ir+YKp/oN12UnBV0YLbyXHrY+y8DWtky7ZS3zkCLsJgsWHW0tVHtnj0xFTtrui7HP5z/9Nu/ctsavKN8GqpjQR9yHhJqLoJCT6IQ2M3slYvW43S5cZDSq0XiAEmxSJ/NU0+qLnySuuA3aujlVLxcyRIxZhHfzaPY/gJzGHmJFHtJmoJsk3aLdS1OButuwDLSpbH/ZtxYwJBNNBYrsr4ofF106qr+WZpNd8J987egv7fnv0vVxVAFIMHX4dQpm5lKiAdvzSrw3cdZWLzn+wfVG8u0bKxTfClQHjnWVPEvxQcyA1Btpk5+h2DDXA9oonp/KWe5YW5omagcDyO5y276MHe8vywWAx41xk9DA="

matrix:
  fast_finish: true

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  #  installation coveralls used to send gcov to coveralls.io
  - pip install --user cpp-coveralls

install:
  # install flex 2.6.4
  - wget https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
  - tar -xzvf flex-2.6.4.tar.gz
  - pushd flex-2.6.4 && ./configure --prefix=/usr && make && sudo make install && popd
  # install bison 3.2
  - wget https://ftp.gnu.org/gnu/bison/bison-3.2.tar.gz
  - tar -xzvf bison-3.2.tar.gz
  - pushd bison-3.2 && ./configure --prefix=/usr && make && sudo make install && popd

script:
  #- export GITHUB_SECRET_TOKEN=[secure]
  - export CC=gcc-7
  - export CXX=g++-7
  - export GCOV=gcov-7
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - sudo ln -s /usr/bin/gcov-7 /usr/local/bin/gcov
  - flex --version && bison --version
  - g++ -v && cmake --version
  - gcov -v
  # generate flex-bison
  - make -C src/parser/flex-bison
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's top-level CMakeLists.txt is located at '..'
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DOPTION_BUILD_TESTS=OFF -DTARGET_CPU=$TARGET_CPU -DCOVERALLS=ON
  - cmake --build .
  # execute tests_run
  - ./bin/tests_run [implemented]

after_success:
  - ls
  #  - coveralls -h
  - cd ..
  - |
    coveralls --build-root build --gcov gcov-7 --gcov-options '\-lp' \
     -e build/src/lib \
     -e build/CMakeFiles \
     -e build/CMakeFiles/feature_tests.c \
     -e build/CMakeFiles/feature_tests.cxx \
     -e src/lib \
     -e src/include \
     -e tests
     -E ".*CMakeFiles.*" \
     -E ".*lib.*"
  - curl -o /tmp/travis-automerge https://raw.githubusercontent.com/kappatych/travis-automerge/master/travis-automerge
  - chmod a+x /tmp/travis-automerge
  - BRANCHES_TO_MERGE_REGEX='^f.*' BRANCH_TO_MERGE_INTO=develop GITHUB_REPO=TrueFinch/kappaDBMS /tmp/travis-automerge